import Head from 'next/head'
import { useState } from 'react';

const Set = () => {
  const [texte, setTexte] = useState('');

  const handleChange = (e) => {
    setTexte(e.target.value);
  };

  const handleClick = () => {
    if (texte.trim()) {
      setTexte('');
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App - Get</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
      <input
        type="text"
        value={texte}
        onChange={handleChange}
        placeholder="Entrez du texte"
      />
      <button onClick={handleClick}>Ajouter</button>
    </div>
    </>
  );
};

export default Set;
